### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...) when mounting/unmounting FormInput

### ISSUE THREAD

**Issue by FullR** [elementalui/elemental#38]
This issue appears to be caused by multiple versions of React being loaded at the same time. I was able to resolve the issue by replacing `import React from "react"` with `import React from "elemental/node_modules/react/addons"` in my top level component, but this does not seem ideal.

Versions:
node 0.12.7
react 0.13.3
elemental 0.3.4

The full error message:
```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): 
Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.invariant 
@ app.js:5718ReactOwner.addComponentAsRefTo 
@ app.js:8811attachRef 
@ app.js:8689ReactRef.attachRefs 
@ app.js:8705attachRefs 
@ app.js:8561assign.notifyAll 
@ app.js:8397ON_DOM_READY_QUEUEING.close 
@ app.js:22635Mixin.closeAll 
@ app.js:9700Mixin.perform 
@ app.js:9641batchedMountComponentIntoNode 
@ app.js:13698Mixin.perform 
@ app.js:9627ReactDefaultBatchingStrategy.batchedUpdates 
@ app.js:20757batchedUpdates 
@ app.js:8154ReactMount._renderNewRootComponent 
@ app.js:13833ReactPerf.measure.wrapper 
@ app.js:8502ReactMount.render 
@ app.js:13922ReactPerf.measure.wrapper 
@ app.js:8502(anonymous function) 
@ app.js:134__webpack_require__ 
@ app.js:20i
@ app.js:40(anonymous function) 
@ app.js:43
```

Here is my render function (compiled using Babel and Webpack):

```javascript
  render() {
    const {username, password, failed} = this.state;
    const {updateUsername, updatePassword} = this;

    return (
      <div>
        <Form>
          {failed ? 
            <Alert type="warning">Invalid username or password</Alert> :
            null
          }
          <FormField label="Username" htmlFor="username">
            <FormInput value={username} onChange={updateUsername} focusOnMount={true} ontype="text" placeholder="Username" name="username"/>
          </FormField>
          <FormField label="Password" htmlFor="password">
            <FormInput value={password} onChange={updatePassword} type="password" placeholder="Password" name="password"/>
          </FormField>
          <Button type="default" onClick={this.submit}>Submit</Button>
        </Form>
      </div>
    );
  }
```

**Comment by nkbt** [comment]
Please install your own react dependency and use `import React from
'react'`. That should fix the issue

**Comment by FullR** [comment]
@nkbt I removed react from my package.json, deleted it from node_modules and reinstalled it using `npm install --save react`, and replaced my import with `import React from "react"`, but I'm still receiving this error.

**Comment by jossmac** [comment]
Glad it's working now @FullR 

Thanks for looking into this @nkbt
